### ISSUE TITLE
FuturVille: Imagining & Building Places Worth Living For - Member request

### ISSUE THREAD

**Issue by AngelaFaye2120** [TrvsGrant/Auravana-Project-Societal-Standard#11]
^^ A title is required above ^^

[PURPOSE] This issue concerns the coordinated admission of new contributing members. 

[INTRODUCTION] Have you ever wanted to contribute to the global human fulfillment through societal design? This template will help a coordinator and "you" to the best understand a good place and position to get started contributing. There is no financial investment to becoming an Auravana contributor, only a time and effort requirement. Minimum time expectations to be a contributor at this phase of development are 7-10 hours per week.

[*WARNING*] This contribution request is public.

[*NOTIFICATION*] You will only be contacted to setup a "meet and greet" for volunteering if you state "Yes" to the required "Yes" sections.

[ACTION] Fill in the template below to complete the request. 

[ MEMBERSHIP REQUEST INQUIRY QUESTIONNAIRE ]

Who are you? 
First Name: Angela 
Last Name: Barnard
Role Identifier: AngelaFaye

Do you agree to all of the following? 
   - I have skills applicable to a societal engineering project.
   - I have a minimum of 7-10 weekly hours to volunteer (20+ for coordination positions).
   - I have communication, project-management, and time-management skills.
   - I am accountable, responsible, and dedicated to producing quality work/end products.
   - I can accomplish all of the above when working under normal, healthy conditions.
---[**Yes** / No]----
YES

Do you agree to the Terms and Conditions and agree to be contacted?
---[Yes / No]----
YES

Do you agree to contribute if you are approved as a volunteer to an Auravana Project Role with Auravana Project tasks/activities, to be held accountable, and to co-operate with others by means of integration, coordination, and communication?
---[Yes / No]----
YES

Are you willing to put effort toward “tangible contribution” that addresses tasks on a globally coordinated Work Breakdown Structure? We differentiate this time from other activities because it directly impacts the completion of a project.
---[Yes / No]----
YES

Do know understand the direction, approach, and overall orientation of the project; do you understand the projects vision for a community-type society? 
---[Yes / No]----
 * If "No", then why?
 * If "Yes", then why?
YES. 
Because I fully believe this vision is possible min 1,000 times in less than 100 years:
The purposeful design of a community-type society offering every individual on the planet a set of highly enriched living opportunities through the union of human fulfillment and scientific possibility. Construction and operation of a global community network with localized integrated city systems, including a multitude of innovative and environmentally friendly technologies directly applied to living systems is already happening and needs support to be implemented 10x smarter, faster, better than ever imagined.  Each 'community' will dramatically reduce suffering, while facilitating the elevation of the well-being of the global population and maximization of everyone’s quality of life, including supporting individual’s intellectual and emotional adaptation to life-oriented, and technically capable, society.

Do know where you can best contribute? (Not a "Yes" required question)?
---[Yes / No]----
 * If "No", then why?
 * If "Yes", then why?
YES.
Public relations. Communications. Broker Agency representation.

How are you qualified to contribute? (Not a "Yes" required question)?
---[Yes / No]----
 * If "No", then why?
 * If "Yes", then why?
YES. I have the mindset, training and energy to contribute. 

How long (weeks, months, years) do you expect to contribute? (Not a "Yes" required question)?
4 hours per month for 100 years

Do you have any references you would like to publicly include (Not a "Yes" required question)?

Do you have any evidence of prior work would like to publicly include (Not a "Yes" required question)?

**Comment by TrvsGrant** [comment]
Meeting complete 19 May 2021.
