### ISSUE TITLE
Contribution membership request

### ISSUE THREAD

**Issue by DaManOme** [TrvsGrant/Auravana-Project-Societal-Standard#16]
^^ A title is required above ^^

[PURPOSE] This issue concerns the coordinated admission of new contributing members. 

[INTRODUCTION] Have you ever wanted to contribute to the global human fulfillment through societal design? This template will help a coordinator and "you" to the best understand a good place and position to get started contributing. There is no financial investment to becoming an Auravana contributor, only a time and effort requirement. Minimum time expectations to be a contributor at this phase of development are 7-10 hours per week.

[*WARNING*] This contribution request is public.

[*NOTIFICATION*] You will only be contacted to setup a "meet and greet" for volunteering if you state "Yes" to the required "Yes" sections.

[ACTION] Fill in the template below to complete the request. 

[ MEMBERSHIP REQUEST INQUIRY QUESTIONNAIRE ]

Who are you? 
First Name: Syed
Last Name: Arif
Role Identifier: Super Cool Coordinator

Do you agree to all of the following? 
   - I have skills applicable to a societal engineering project.
   - I have a minimum of 7-10 weekly hours to volunteer (20+ for coordination positions).
   - I have communication, project-management, and time-management skills.
   - I am accountable, responsible, and dedicated to producing quality work/end products.
   - I can accomplish all of the above when working under normal, healthy conditions.
---[Yes]----

Do you agree to the Terms and Conditions and agree to be contacted?
---[Yes]----

Do you agree to contribute if you are approved as a volunteer to an Auravana Project Role with Auravana Project tasks/activities, to be held accountable, and to co-operate with others by means of integration, coordination, and communication?
---[Yes]----

Are you willing to put effort toward “tangible contribution” that addresses tasks on a globally coordinated Work Breakdown Structure? We differentiate this time from other activities because it directly impacts the completion of a project.
---[Yes]----

Do you understand the direction, approach, and overall orientation of the project; do you understand the project's vision for a community-type society? 
---[Yes]----
 * If "Yes", then why?
We're doing a new way of life without money and coercion to achieve the best standard of life possible for the betterment of all. By doing that we need to be able to raise our standards to meet & exceed those standards to experience and enjoy the community/lifestyle we all want and deserve!

Do know where you can best contribute? (Not a "Yes" required question)?

Everywhere, this lifestyle is me, whatever I utilize and do is me contributing to the betterment of all. I'm a visionary-ideas guy and I want people to be excited to live this lifestyle now and into the future!

How are you qualified to contribute? (Not a "Yes" required question)?

I'm a living being, therefore I contribute to making my life and others the most enjoyable life experience possible

How long (weeks, months, years) do you expect to contribute? (Not a "Yes" required question)?

The rest of my life!

Do you have any references you would like to publicly include (Not a "Yes" required question)?

You lol

Do you have any evidence of prior work would like to publicly include (Not a "Yes" required question)?

Nope :P

**Comment by TrvsGrant** [comment]
This contribution membership request is being closed because it has been open for more than one month and the project has not received the necessary email to continue this request. Contribution membership requests that have been open for one month without a project coordinator receiving the agreement email will be closed per project procedures. If you would like to contribute, please make another contribution request and submit the appropriate email per procedure.
