### ISSUE TITLE
Issue: Contribution Membership Request

### ISSUE THREAD

**Issue by lunarlexa** [TrvsGrant/Auravana-Project-Societal-Standard#25]
^^ A title is required above ^^

[PURPOSE] This issue concerns the coordinated admission of new contributing members. 

[INTRODUCTION] Have you ever wanted to contribute to the global human fulfillment through societal design? Yes. I believe the Capitalist society we now live in is not optimal for the development and evolution of humankind. 

[ACTION] Fill in the template below to complete the request. 

[ MEMBERSHIP REQUEST INQUIRY QUESTIONNAIRE ]

Who are you? 
First Name: Alexa
Last Name: Rodriguez
Role Identifier: Spiritual Practitioner/Advisor and Revolutionary. 

Do you agree to all of the following? 
   - I have skills applicable to a societal engineering project. Yes
   - I have a minimum of 7-10 weekly hours to volunteer (20+ for coordination positions). Yes
   - I have communication, project-management, and time-management skills. Yes
   - I am accountable, responsible, and dedicated to producing quality work/end products. Yes
   - I can accomplish all of the above when working under normal, healthy conditions. Yes

Do you agree to the Terms and Conditions and agree to be contacted? Yes

Do you agree to contribute if you are approved as a volunteer to an Auravana Project Role with Auravana Project tasks/activities, to be held accountable, and to co-operate with others by means of integration, coordination, and communication? Yes

Are you willing to put effort toward “tangible contribution” that addresses tasks on a globally coordinated Work Breakdown Structure? We differentiate this time from other activities because it directly impacts the completion of a project. Yes

Do you understand the direction, approach, and overall orientation of the project; do you understand the projects vision? 

 * If "Yes", then why? Yes, from what I've gathered the vision of the project is to be a classless, moneyless and free community led society where human beings can tune into their soul, allowing them to become more in touch with their purpose and need for evolution to ensure a full, peaceful and enjoyable human experience and life. 

Do you know where you can best contribute? (Not a "Yes" required question)?

 * If "Yes", then why? My most tangible skills have been in project management where I've have employees and clients follow me to other places of business because they've always felt seen, heard and trust from me. I also have experience in social media marketing and events where I learned how to showcase and make human connections both in person and on social media platforms. I am also a spiritual practitioner of 6 years where I am able to help a collective audience find their spiritual strength and development through channeled messages and divination. 

How are you qualified to contribute? (Not a "Yes" required question)?

 * If "Yes", then why? I feel I can best contribute to this project with my drive alone. I have learned many skills, joined many organizations and worked in many industries where I had big ideas and ways to help these projects thrive. Some ideas were taken from me without credit causing me to leave and others not allowing me to speak due to the power structure that the lowly worker is not allowed to speak against. I have yet to find a place that I feel is ready for my assistance, contribution and leadership. 

How long (weeks, months, years) do you expect to contribute?
I feel like this project is aligned to my souls purpose and mission. I will contribute as long as I need to so we can enact change in a broken system of suffering. 

Do you have any references you would like to publicly include 
No.

Do you have any evidence of prior work would like to publicly include.
No.

**Comment by TrvsGrant** [comment]
> ^^ A title is required above ^^
> 
> [PURPOSE] This issue concerns the coordinated admission of new contributing members. 
> 
> [INTRODUCTION] Have you ever wanted to contribute to the global human fulfillment through societal design? Yes. I believe the Capitalist society we now live in is not optimal for the development and evolution of humankind. 
> 
> [ACTION] Fill in the template below to complete the request. 
> 
> [ MEMBERSHIP REQUEST INQUIRY QUESTIONNAIRE ]
> 
> Who are you? 
> First Name: Alexa
> Last Name: Rodriguez
> Role Identifier: Spiritual Practitioner/Advisor and Revolutionary. 
> 
> Do you agree to all of the following? 
>    - I have skills applicable to a societal engineering project. Yes
>    - I have a minimum of 7-10 weekly hours to volunteer (20+ for coordination positions). Yes
>    - I have communication, project-management, and time-management skills. Yes
>    - I am accountable, responsible, and dedicated to producing quality work/end products. Yes
>    - I can accomplish all of the above when working under normal, healthy conditions. Yes
> 
> 
> Do you agree to the Terms and Conditions and agree to be contacted? Yes
> 
> 
> Do you agree to contribute if you are approved as a volunteer to an Auravana Project Role with Auravana Project tasks/activities, to be held accountable, and to co-operate with others by means of integration, coordination, and communication? Yes
> 
> 
> Are you willing to put effort toward “tangible contribution” that addresses tasks on a globally coordinated Work Breakdown Structure? We differentiate this time from other activities because it directly impacts the completion of a project. Yes
> 
> Do you understand the direction, approach, and overall orientation of the project; do you understand the projects vision? 
> 
>  * If "Yes", then why? Yes, from what I've gathered the vision of the project is to be a classless, moneyless and free community led society where human beings can tune into their soul, allowing them to become more in touch with their purpose and need for evolution to ensure a full, peaceful and enjoyable human experience and life. 
> 
> Do you know where you can best contribute? (Not a "Yes" required question)?
> 
>  * If "Yes", then why? My most tangible skills have been in project management where I've have employees and clients follow me to other places of business because they've always felt seen, heard and trust from me. I also have experience in social media marketing and events where I learned how to showcase and make human connections both in person and on social media platforms. I am also a spiritual practitioner of 6 years where I am able to help a collective audience find their spiritual strength and development through channeled messages and divination. 
> 
> How are you qualified to contribute? (Not a "Yes" required question)?
> 
>  * If "Yes", then why? I feel I can best contribute to this project with my drive alone. I have learned many skills, joined many organizations and worked in many industries where I had big ideas and ways to help these projects thrive. Some ideas were taken from me without credit causing me to leave and others not allowing me to speak due to the power structure that the lowly worker is not allowed to speak against. I have yet to find a place that I feel is ready for my assistance, contribution and leadership. 
> 
> How long (weeks, months, years) do you expect to contribute?
> I feel like this project is aligned to my souls purpose and mission. I will contribute as long as I need to so we can enact change in a broken system of suffering. 
> 
> Do you have any references you would like to publicly include 
> No.
> 
> Do you have any evidence of prior work would like to publicly include.
> No. 
> 


Greetings Alexa, how do I contact you?

**Comment by TrvsGrant** [comment]
Greetings Alexa. Thank you for filling out the contribution form. Let's schedule a meet and greet between us. What method of contact is best for you?

**Comment by lunarlexa** [comment]
Hello! You can contact me over phone or through email here. Whichever fits
best!

2104196879

**Comment by TrvsGrant** [comment]
Shall we schedule a meet and greet for later this week? I am east coast US time. I am free in the afternoon and evening Wednesday through Saturday this week.  Wednesday I am free after 1500. What time and date works best for you? Does this week work, or we can schedule for next week. 

Look forward to speaking with you. 
Best, 
Travis Grant

**Comment by lunarlexa** [comment]
So it looks like I can make Thursday anytime after 3:00PM eastern time.

Do you want to shoot for 3:30PM on Thursday?

**Comment by TrvsGrant** [comment]
Excellent. This Thursday at 3:30. I have made a Google Calendar invite for the meeting:

Travis & Alexa
Nov 14  •  15:30 – 16:15  •  View details & RSVP https://calendar.app.google/1j4EzpgKpctHzGJh8

Look forward to meeting you. 
Best, 
Travis

**Comment by TrvsGrant** [comment]
Greetings Alexa. It looks like you missed the meeting. I tried to email you after the meeting, but the email didn't go through and was returned to sender. Would you like to reschedule?

**Comment by TrvsGrant** [comment]
Alexa did not show to any meetings or get back in touch. This issue has been closed.
